### ISSUE TITLE
"Edge vector" error during signal extraction

### ISSUE THREAD

**Issue by omidm7** [bahanonu/calciumImagingAnalysis#11]
Hey Biafra,

After running cnmf-e or PCA/ICA, I get the same error:
![image](https://user-images.githubusercontent.com/44180252/51935144-1681b800-23ba-11e9-9139-326a3bc47a20.png)

Here is an example of how I get there, perhaps there is a mistake along the way?
![image](https://user-images.githubusercontent.com/44180252/51935206-416c0c00-23ba-11e9-98a3-c2c2256c3cb7.png)
(Here I'm still using 'crop' because I chose not to manually modify the movie.)

![image](https://user-images.githubusercontent.com/44180252/51935260-5d6fad80-23ba-11e9-9675-92956369f342.png)

Then the following Finder window opens up. I'm not sure which file to open here. I tried opening a few different ones, but all led to the same error.
![image](https://user-images.githubusercontent.com/44180252/51935472-d40cab00-23ba-11e9-86e1-985efe63e2ac.png)

Omid

**Comment by bahanonu** [comment]
@omidm7 

Can you copy and paste your command window or link as a text file for both PCA-ICA and CNMF-E cases? The `histc` (within `viewCreateObjmaps` that runs after cell extraction) error is normally caused by PCA-ICA or one of the other cell extraction functions failing and not producing an output.

As a heads up, made several updates so might want to re-pull the master.

**Comment by bahanonu** [comment]
@omidm7 
And as a heads up, delete the file with `medianFilter...` as that appears to be incorrect (e.g. no need to do both dfof and dfstd on the same movie). It is possible that file is being passed to PCA-ICA and CNMF-E since it would be the 1st one in the sort order and likely doesn't have sensible pixel values that either algorithm can use to pull out cells.

**Comment by omidm7** [comment]
Ok, so I just re-pulled the master, and am trying to run downloadCnmfGithubRepositories.m
![image](https://user-images.githubusercontent.com/44180252/51937083-842fe300-23be-11e9-9e5d-21ac8847bd48.png)

When this window comes up. I haven't seen this before. Should I open cvc_startup.m?
![image](https://user-images.githubusercontent.com/44180252/51937110-990c7680-23be-11e9-8437-57484c4120e8.png)

**Comment by omidm7** [comment]
Ok, deleting cnmfe zip and re-downloading from your link seems to have fixed it! Now cnmfe is running.
By the way, I don't get instructions like 'Select cvx_setup.m' whenever a dialog box opens, which is why it's been a little confusing. But it's not the biggest issue. Thanks again, man.
Omid

**Comment by bahanonu** [comment]
Sounds good. fyi, appears that the dialog box display style isn't under Matlab control and others have noted that in newer OSX versions the dialog boxes don't display titles. I'll just add a note in the command window duplicating title for those on OSes without dialog box titles.

**Comment by bahanonu** [comment]
Great!

The black areas in the 2nd picture indicate that at the default event detection threshold, the candidate cell did not have 14 calcium transients so I place blank panels (keeping the same size grid as less jarring for users).

If you press `w` while in the interface (allows you to change the trace y-axis) and change the min/max to min = 0 and max = [0.3 or 2], what do the traces look like? Given the movie transients are correct, appears that there might be a trace that has really high values and is throwing off the y-axis for the traces (I try and keep they y-axis constant during sorting by calculating a reasonable max based on all cells' traces).

It looks like you might have something going on around the edges of the movie (hence the bright vertical/horizontal 'cell' outputs), so might consider cropping those out if haven't done so already.
https://github.com/bahanonu/calciumImagingAnalysis#manual-movie-cropping-with-modelmodifymovies

**Comment by bahanonu** [comment]
For example

## Can't see transients.

![image](https://user-images.githubusercontent.com/5241605/51950315-d84dbe00-23e4-11e9-9a5d-5d34e7c6ed39.png)

## Change the min/max.
![image](https://user-images.githubusercontent.com/5241605/51950356-07fcc600-23e5-11e9-9166-71282d774cea.png)

## Can now see transients.
![image](https://user-images.githubusercontent.com/5241605/51950282-bb18ef80-23e4-11e9-8c52-5649175fb0fb.png)

**Comment by bahanonu** [comment]
For example:

## Can't see transients.

![image](https://user-images.githubusercontent.com/5241605/51950315-d84dbe00-23e4-11e9-9a5d-5d34e7c6ed39.png)

## Change the min/max.
![image](https://user-images.githubusercontent.com/5241605/51950356-07fcc600-23e5-11e9-9166-71282d774cea.png)

## Can now see transients.
![image](https://user-images.githubusercontent.com/5241605/51950282-bb18ef80-23e4-11e9-8c52-5649175fb0fb.png)

**Comment by omidm7** [comment]
Thanks for the info about the panels, @bahanonu !
You are right, those bright vertical and horizontal bars were throwing all values off. I think I finally got rid of them.
I decided to upload only one Tiff instead of three in the root folder to make things go faster while I work out the bugs. However, when I get to the manualSortsignal module, I'm getting this error. It seems like it doesn't like the fact that it's a single file?

![image](https://user-images.githubusercontent.com/44180252/52023724-1dd8bc80-24b3-11e9-9058-569c7c9da0c1.png)
![image](https://user-images.githubusercontent.com/44180252/52023754-406ad580-24b3-11e9-87bc-9e664d5f8966.png)

**Comment by bahanonu** [comment]
@omidm7 

What files are in the directory and can you give me the output of the below? 
- Substituting PATH for the absolute path to the processed HDF5 movie containing either 'crop' or 'manualCut' in the name
- And substituting FOLDER_PATH for `/Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01`.

```Matlab
loadMovieList('PATH','getMovieDims',1)
cellfun(@disp,getFileList(FOLDER_PATH, 'crop'))
```

**Comment by omidm7** [comment]
Sure! Here's a screenshot of the files in the directory:
![image](https://user-images.githubusercontent.com/44180252/52024520-f7685080-24b5-11e9-9d5f-7712115f0c02.png)

And the output of the lines:
![image](https://user-images.githubusercontent.com/44180252/52024757-c89eaa00-24b6-11e9-90f1-ac1c53b9abbd.png)

**Comment by bahanonu** [comment]
Gotcha, delete `2019_01_29_p001_m001_baseline01_turboreg_crop_1_source_extraction` then you should re-run CNMF-E with either 'dfof' or 'downsample' (the latter if you want to use the temporally downsampled file for analysis) as the regular expressions file since it appears you selected to also output files after the 'crop' step (if you don't need this for a specific reason, I'd avoid selecting that as an output in the preprocessing module), so it is searching and finding that file first then running CNMF-E on it.

![image](https://user-images.githubusercontent.com/5241605/52025113-1831a580-24b8-11e9-8540-9107abec9db3.png)

For `loadMovieList` can you give me the output of
```Matlab
loadMovieList(getFileList('/Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01', 'crop'),'getMovieDims',1)
```

**Comment by omidm7** [comment]
Cool, thanks! I'll run cnmf-e again with those parameters changed.

Here is the output of that line:
![image](https://user-images.githubusercontent.com/44180252/52025590-bd994900-24b9-11e9-8f68-3f470be26d90.png)

**Comment by bahanonu** [comment]
Sounds good. Will also see about deleting the temporary folder CNMF-E creates (duplicates the movie data) as this can get large/problematic at times.

And lastly, can you give me the output of the below, want to see the HDF5 info.

```Matlab
loadMovieList(getFileList('/Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01', 'crop'),'getMovieDims',1,'displayDiagnosticInfo',1)
```

**Comment by bahanonu** [comment]
That works. I'll modify `computeCnmfeSignalExtraction` and the extraction module to allow modification of the memory requirement (e.g. see below for the defaults currently). I haven't done systematic memory parameter sweeps with CNMF-E yet to see how patch size effects runtime, can get back on that.

```Matlab
pars_envs = struct('memory_size_to_use', 8, ...   % GB, memory space you allow to use in MATLAB
    'memory_size_per_patch', 0.6, ...   % GB, space for loading data within one patch
    'patch_dims', [64, 64]);  %GB, patch size
```

**Comment by omidm7** [comment]
Hi,
Here's the output for the HDF5 info:

`loadMovieList(getFileList('/Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01', 'crop'),'getMovieDims',1,'displayDiagnosticInfo',1)
MATLAB has lost its connection to the license server.
MATLAB will make 9 more reconnection attempt(s) and then exit. Any unsaved changes will be lost.

###
removing unsupported file from list: /Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01/2019_01_29_p001_m001_baseline01_turboreg_crop_dfof_1_source_extraction

hReadInfo = 

  struct with fields:

      Filename: '/Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01/2019_01_29_p001_m001_baseline01_turboreg_crop_1.h5'
          Name: '/1'
          Rank: 3
      Datatype: [1×1 struct]
          Dims: [150 200 18000]
       MaxDims: [150 200 18000]
        Layout: 'chunked'
    Attributes: []
         Links: []
     Chunksize: [150 200 1]
     FillValue: 0


ans =

    '/1'

loading chunk | offset: 0  0  1 | block: 150  200    1

movie size: 0.11444Mb | 150  200 | single

hReadInfo = 

  struct with fields:

      Filename: '/Users/Bing/calciumImagingAnalysis/data/2019_01_29_p001_m001_baseline01_trial01/2019_01_29_p001_m001_baseline01_turboreg_crop_dfof_1.h5'
          Name: '/1'
          Rank: 3
      Datatype: [1×1 struct]
          Dims: [150 200 18000]
       MaxDims: [150 200 18000]
        Layout: 'chunked'
    Attributes: []
         Links: []
     Chunksize: [150 200 1]
     FillValue: 0


ans =

    '/1'

loading chunk | offset: 0  0  1 | block: 150  200    1

movie size: 0.11444Mb | 150  200 | single
Index exceeds matrix dimensions.

Error in loadMovieList (line 216)
		if (~isempty(options.frameList)|options.frameList>dims.z(iMovie))&options.treatMoviesAsContinuous==0
 
>> `

**Comment by bahanonu** [comment]
Thanks, pull the master, updated to deal with this. Let me know if anything else comes up. 

Remember in `computeManualSortSignals` to change the movie file filter (see below). You can also choose `other (manually enter name)` option if you want to manually select a specific movie file, just make sure the same one ran with CNMF-E or ICA.

![image](https://user-images.githubusercontent.com/5241605/52075244-aa7d8c00-2540-11e9-8980-f810a97fe476.png)

**Comment by omidm7** [comment]
Sounds good! I was just able to get through the entire computeManualSortSignals.
I'm gonna pull the master again now, but I think everything should be ok. :) 
Omid

**Comment by bahanonu** [comment]
Hey Omid,

A couple things (esp. if you have neuropil in your movies), should likely include a note about this in the readme. 

## Movie cell ROI trace during cell sorting
- If you press `r` while in the interface, it will show you a ROI calculated trace (which will contain more cross-talk, but will give you a direct measure of ΔF/F from your movie compared to CNMF-E trace.
![image](https://user-images.githubusercontent.com/5241605/52152675-0ffa7700-262c-11e9-9800-e53517cde869.png)
![image](https://user-images.githubusercontent.com/5241605/52152685-1a1c7580-262c-11e9-9beb-e47fa5ffeac9.png)

## spatial filtering during preprocess
- The other is that in the preprocessing module, when you are on the 1st page of the options, in the `filterBeforeRegister` setting select `matlab divide by lowpass before registering` or `matlab bandpass before registering`.
- See also the spatial filtering wiki page: https://github.com/bahanonu/calciumImagingAnalysis/wiki/Preprocessing:-Spatial-filtering#dark-halos-around-cells.
![image](https://user-images.githubusercontent.com/5241605/52152666-06710f00-262c-11e9-89fe-6f517632f384.png)

## viewMovieRegistrationTest
- To get a feel for how the different filtering affects SNR/movie data, run `viewMovieRegistrationTest` module and select either `matlab divide by lowpass before registering` or `matlab bandpass before registering` then change `filterBeforeRegFreqLow` and `filterBeforeRegFreqHigh` settings, see below.
![image](https://user-images.githubusercontent.com/5241605/52153165-cb6fdb00-262d-11e9-8c9f-8e7953c02eee.png)

![image](https://user-images.githubusercontent.com/5241605/52152814-a62e9d00-262c-11e9-99da-981377a4b7b9.png)
- You'll get an output like the below (top left is without any filtering, other 3 are with different bandpass filtering options).
![image](https://user-images.githubusercontent.com/5241605/52153455-f3137300-262e-11e9-9858-45445f44e7f5.png)
![image](https://user-images.githubusercontent.com/5241605/52153507-2d7d1000-262f-11e9-9662-182331b555c0.png)


- Cell ΔF/F intensity profile from the raw movie 
![image](https://user-images.githubusercontent.com/5241605/52153427-d7a86800-262e-11e9-983f-fa3879adca9a.png)

- Same cell ΔF/F intensity profile from the bottom/left movie (not the y-axis is the same as above):
![image](https://user-images.githubusercontent.com/5241605/52153392-ba739980-262e-11e9-8750-04ef2c11861b.png)

**Comment by omidm7** [comment]
Hey Biafra,
Just wanted to update you. I played around with the image registration parameters and found that low freq of 2 and hi of 60 works best for my videos. Also, I am using imtransform instead of turboreg because of the dropped frames issue. 
Check out the difference!
![image](https://user-images.githubusercontent.com/44180252/52382967-44a36f80-2a2c-11e9-95b4-e2bfe6502824.png)

I have a question about the final output. In the readme, you say the PCA/ICA output is an [n f] matrix with f representing the number of frames. Is this the same structure for the cnmfe output? My original movie had about 95K frames and the cnmfe analysis matrix has 11.2K columns. Also check out the x-axis below. I assume this is because of downsampling, but just want to confirm the x-axis is correct and still representing frames, not time. (PS my video was recorded at 30 fps.)
Omid
![image](https://user-images.githubusercontent.com/44180252/52383195-386be200-2a2d-11e9-9ad9-3071c83757e8.png)

**Comment by bahanonu** [comment]
@omidm7 

Awesome, great to hear! 

Yep, cnmfe has a similar structure for the `extractedSignals`, `extractedSignalsEst`, and `extractedPeaks`. I'll add that note to the README.

Could you send over the output of below? Replace `FOLDERPATH` with the full folder path. Want to first check the input or raw has 95k frames before further debugging.
```Matlab
loadMovieList(getFileList('FOLDERPATH', 'crop|concat'),'getMovieDims',1,'displayDiagnosticInfo',1)
```

(p.s. as a heads up, the frames aren't dropped with `transfturboreg`, just the baseline will shift, on the backend it is using turboreg to get the registration coordinates then using `imtransform` to do the actual shifting of each frame).

**Comment by omidm7** [comment]
Ok, here is the output for that line. (BTW the # of frames is actually 45,060, not 95k.)
![image](https://user-images.githubusercontent.com/44180252/52388627-28133180-2a44-11e9-897d-634949d8adbf.png)

`>> loadMovieList(getFileList('/Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01', 'crop|concat'),'getMovieDims',1,'displayDiagnosticInfo',1)
###
removing unsupported file from list: /Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01/2018_12_23_p001_m01_baseline01_stripeRemoval_turboreg_crop_dfof_downsampleTime_1_source_extraction
Getting movie info for 1\4: /Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01/2018_12_23_p001_m01_baseline01_stripeRemoval_turboreg_crop_dfof_downsampleTime_1.h5

hReadInfo = 

  struct with fields:

      Filename: '/Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01/2018_12_23_p001_m01_baseline01_stripeRemoval_turboreg_crop_dfof_downsampleTime_1.h5'
          Name: '/1'
          Rank: 3
      Datatype: [1×1 struct]
          Dims: [150 200 11265]
       MaxDims: [150 200 11265]
        Layout: 'chunked'
    Attributes: []
         Links: []
     Chunksize: [150 200 1]
     FillValue: 0


ans =

    '/1'

loading chunk | offset: 0  0  1 | block: 150  200    1

movie size: 0.11444Mb | 150  200 | single
Getting movie info for 2\4: /Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01/concat_phil_25_min_1.tif
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50838 (0xc696) encountered.' 
> In Tiff (line 651)
  In loadMovieList (line 152) 
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50839 (0xc697) encountered.' 
> In Tiff (line 651)
  In loadMovieList (line 152) 
Getting movie info for 3\4: /Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01/concat_phil_25_min_2.tif
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50838 (0xc696) encountered.' 
> In Tiff (line 651)
  In loadMovieList (line 152) 
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50839 (0xc697) encountered.' 
> In Tiff (line 651)
  In loadMovieList (line 152) 
Getting movie info for 4\4: /Users/Bing/calciumImagingAnalysis/data/2018_12_23_p001_m01_baseline01_trial01/concat_phil_25_min_3.tif
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50838 (0xc696) encountered.' 
> In Tiff (line 651)
  In loadMovieList (line 152) 
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 50839 (0xc697) encountered.' 
> In Tiff (line 651)
  In loadMovieList (line 152) 
checking movies: 100.00%
Elapsed time is 9.624162 seconds.
###

ans = 

  struct with fields:

        x: [150 150 150 150]
        y: [200 200 200 200]
        z: [11265 18000 18000 9060]
      one: [150 150 150 150]
      two: [200 200 200 200]
    three: [11265 18000 18000 9060]

>> `

**Comment by bahanonu** [comment]
The 11,265 frames makes sense in this case since the raw movie is 45,060 and the default `downsampleTime` is 4x. If you want, you can either de-select downsampleTime as a pre-processing step or output both the dfof and downsampleTime step then change the movie regexp to `dfof_1` in `modelExtractSignalsFromMovie` so CNMF-E runs on the non-downsampled movie.

![image](https://user-images.githubusercontent.com/5241605/52397535-c3b79880-2a6a-11e9-9187-bf857ddf83e5.png)

**Comment by omidm7** [comment]
What's up, Biafra. Do you have an easy way to extract the # of peaks for a given cell? I thought I could get it from the number of non-zero elements given by cnmfeAnalysisOutput.extractedPeaks, but didn't realize extractedPeaks was giving out values to reconstruct a peak. For example, below is an output of cnmfeAnalysisOutput.extractedPeaks for a single cell. 

![image](https://user-images.githubusercontent.com/44180252/52676666-c2112900-2edf-11e9-9aa9-21b178696d2b.png)

**Comment by bahanonu** [comment]
@omidm7 

Yep, you can use the `computeSignalPeaks` function to extract calcium transients. The main Name-Value pairs to consider are `numStdsForThresh`, `detectMethod`, `medianFilterLength`, and `minTimeBtEvents` (see https://github.com/bahanonu/calciumImagingAnalysis/blob/master/signal_processing/computeSignalPeaks.m#L47). Let me know if that works for you.

```Matlab
computeSignalPeaks(cnmfeAnalysisOutput.extractedSignals,'makePlots',0,'numStdsForThresh',2.3,'detectMethod','raw','medianFilterLength',1000,'minTimeBtEvents',4);
```

For testing, you can run with `makePlots = 0` as below and a GUI will appear that can let you see the detected peaks are your chosen parameters (and you can zoom in on the bottom graph to get a closer look at the peak estimation and timing).

```Matlab
computeSignalPeaks(cnmfeAnalysisOutput.extractedSignals,'makePlots',1,'numStdsForThresh',2.3,'detectMethod','raw','medianFilterLength',1000,'minTimeBtEvents',4);
```

![20190208_examplecell_peaks](https://user-images.githubusercontent.com/5241605/52680277-bd9f3d00-2eec-11e9-9cfe-b4b98adcd89e.PNG)

**Comment by omidm7** [comment]
Awesome, thanks, I got that GUI to work and tested it. Now that I found the right settings for computesignalpeaks, do I have to run cnmfe again to apply those changes to my data set?

**Comment by bahanonu** [comment]
Great, good to hear. Nope, you can just run `cnmfeAnalysisOutput.extractedSignals` through

```Matlab
[signalPeaks, signalPeaksArray,~] = computeSignalPeaks(cnmfeAnalysisOutput.extractedSignals,'makePlots',0,'numStdsForThresh',2.3,'detectMethod','raw','medianFilterLength',1000,'minTimeBtEvents',4);
```

Where `signalPeaks` and `signalPeaksArray` are your calcium transients.

```Matlab
% signalPeaks: [nSignals frame] matrix. Binary matrix with 1 = peaks.
% signalPeaksArray: {1 nSignals} cell array. Each cell contains [1 nPeaks] vector that stores the frame locations of each peak.
```

I normally do this after cell extraction in whatever analysis scripts I am using to make sure all animals run through the same event detection.

**Comment by omidm7** [comment]
Thanks so much!
